#! /bin/sh

# https://sourceforge.net/p/sox/bugs/363
# sox segfaults when parsing CLI options

# 14.4.2

# sox_ng-14.5.0

# Debian

# 42b355

rm -f core

${sox:-sox} -V -V --norm ../../src/monkey.wav -d
status=$?

rm -f core

exit $status
