#! /bin/sh

# Check 50:50 mix is a no-op for --combine mix

set -e

rm -f sweep.wav out.wav

status=0

${sox:-sox} -D -n -b 16 -e signed sweep.wav synth 10 sine 27.5/14080
${sox:-sox} -D --combine mix sweep.wav sweep.wav out.wav
cmp -s sweep.wav out.wav || status=2

rm sweep.wav out.wav

exit $status
