#! /bin/sh

# sox.sf.net patch 126: Global-buffer-overflow at `adpcms.c:58`
# https://sourceforge.net/p/sox/patches/126

# You have to compile it with the address sanitizer to see the failure.
# ./configure CFLAGS=-fsanitize=address LDFLAGS=-lasan

rm -f core out.*

${sox:-sox} crash-gbo-voc out.wav
status=$?

rm -f core out.*

exit $status
