#! /bin/sh

# Check 50:50 mix is a no-op for --combine mix

set -e

rm -f audio.wav out.wav

status=0

${sox:-sox} -D -n -b 16 -e signed audio.wav synth 10 sine 27.5-14080
${sox:-sox} -D audio.wav out.wav synth 10 sine mix 27.5-14080
cmp -s audio.wav out.wav || status=2

rm audio.wav out.wav

exit $status
