#! /bin/sh

# Test writing of AIFC ALAW encoding

rm -f core out.aifc alaw.wav out.wav

${sox:-sox} alaw.aifc -e a-law out.aifc
status=$?

${sox:-sox} alaw.aifc -e signed -b 16 alaw.wav || status=2
${sox:-sox} out.aifc -e signed -b 16 out.wav || status=2
cmp alaw.wav out.wav || status=2

rm -f core out.aifc alaw.wav out.wav

exit $status
